name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  hive: ^2.2.3
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  dartz: ^0.10.1
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^16.0.0
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  app_links: ^6.4.0
  firebase_analytics: ^12.0.0
  uuid: ^4.5.1
  device_info_plus: ^11.5.0
  internet_connection_checker: ^1.0.0+1
  appsflyer_sdk: ^6.16.21
  permission_handler: ^12.0.1
  image_cropper: ^9.1.0
  image: ^4.5.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0
  firebase_core: ^4.0.0
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.2.1
  webview_flutter: ^4.13.0
  flutter_rating: ^2.0.2
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1
  easy_localization: ^3.0.8
  flutter_phoenix: ^1.1.1
  supabase_flutter: ^2.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.6.2
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/general-sans/
    - assets/icons/
    - assets/icons/home/
    - assets/images/
    - assets/translations/
    - assets/projectIcon/
    - assets/.env


  fonts:
    - family: general-sans
      fonts:
        - asset: assets/fonts/general-sans/GeneralSans-Bold.otf
        - asset: assets/fonts/general-sans/GeneralSans-BoldItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Extralight.otf
        - asset: assets/fonts/general-sans/GeneralSans-ExtralightItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Italic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Light.otf
        - asset: assets/fonts/general-sans/GeneralSans-LightItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Medium.otf
        - asset: assets/fonts/general-sans/GeneralSans-MediumItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Regular.otf
        - asset: assets/fonts/general-sans/GeneralSans-Semibold.otf
        - asset: assets/fonts/general-sans/GeneralSans-SemiboldItalic.otf

