name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get_it: ^8.0.3
  injectable: ^2.5.0
  hive: ^2.2.3
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  dartz: ^0.10.1
  network_info_plus: ^6.1.4
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^16.0.0
  connectivity_plus: ^6.1.4
  confetti: ^0.8.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  app_links: ^6.4.0
  firebase_analytics: ^12.0.0
  uuid: ^4.5.1
  device_info_plus: ^11.5.0
  internet_connection_checker: ^1.0.0+1
  appsflyer_sdk: ^6.16.21
  tiktok_events_sdk: ^1.0.9
  permission_handler: ^12.0.1
  image_cropper: ^9.1.0
  image: ^4.5.4
  image_picker: ^1.1.2
  audioplayers: ^6.5.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  flutter_localization: ^0.3.3
  firebase_core: ^4.0.0
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.2.1
  sms_autofill: ^2.4.1
  flutter_rating: ^2.0.2
  syncfusion_flutter_gauges: ^30.1.42
  webview_flutter: ^4.13.0
  syncfusion_flutter_pdfviewer: ^30.1.42
  animate_do: ^4.2.0
  chewie: ^1.12.1
  flutter_inappwebview: ^6.1.5
  showcaseview: ^4.0.1
  flutter_rating_bar: ^4.0.1
  screen_protector: ^1.4.2+1
  percent_indicator: ^4.2.5
  flutter_staggered_grid_view: ^0.7.0
  app_settings: ^6.1.1
  share_plus: ^11.0.0
  carousel_slider: ^5.1.1
  background_downloader: ^9.2.3
  pin_code_fields: ^8.0.1
  in_app_review: ^2.0.10
  hijri: ^3.0.0
  easy_stepper: ^0.8.5+1
  easy_localization: ^3.0.8
  flutter_phoenix: ^1.1.1

  json_annotation: ^4.9.0
  supabase_flutter: ^2.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.6.2
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/general-sans/
    - assets/icons/
    - assets/icons/home/
    - assets/images/
    - assets/lottie/
    - assets/translations/
    - assets/projectIcon/

  fonts:
    - family: general-sans
      fonts:
        - asset: assets/fonts/general-sans/GeneralSans-Bold.otf
        - asset: assets/fonts/general-sans/GeneralSans-BoldItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Extralight.otf
        - asset: assets/fonts/general-sans/GeneralSans-ExtralightItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Italic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Light.otf
        - asset: assets/fonts/general-sans/GeneralSans-LightItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Medium.otf
        - asset: assets/fonts/general-sans/GeneralSans-MediumItalic.otf
        - asset: assets/fonts/general-sans/GeneralSans-Regular.otf
        - asset: assets/fonts/general-sans/GeneralSans-Semibold.otf
        - asset: assets/fonts/general-sans/GeneralSans-SemiboldItalic.otf
