import 'package:ecommerce_app/config/resources/app_constants.dart';
import 'package:ecommerce_app/config/resources/app_shadow.dart';
import 'package:ecommerce_app/config/resources/app_strings.dart';
import 'package:ecommerce_app/core/responsive_manager/responsive_extensions.dart';
import 'package:ecommerce_app/core/responsive_manager/spacing_facade.dart';
import 'package:ecommerce_app/core/shared_widget/buttons/button_widget.dart';
import 'package:ecommerce_app/core/shared_widget/custom_inkwell.dart';
import 'package:ecommerce_app/core/shared_widget/nullable_network_image.dart';
import 'package:ecommerce_app/core/text_styling/extensions/app_text_theme.dart';
import 'package:ecommerce_app/core/theme_manager/service/app_colors.dart';
import 'package:ecommerce_app/features/shared_features/header_for_more.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';

import '../../../../config/base_local_data_source/base_local_data_source.dart';
import '../../../../config/base_remote_data_source/base_remote_data_source.dart';
import '../../../../config/base_repository/base_repository.dart';

part 'data/cart_data_source/cart_local_data_source.dart';
part 'data/cart_data_source/cart_remote_data_source.dart';
part 'data/cart_models/cart_entity.dart';
part 'data/cart_models/cart_model.dart';
part 'data/cart_repository/cart_repository.dart';
part 'logic/cart_cubit.dart';
part 'logic/cart_state.dart';
part 'ui/cart_screen/cart_screen.dart';
part 'ui/cart_widgets/cart_widgets.dart';
