import 'package:dartz/dartz.dart' hide State;
import 'package:ecommerce_app/config/resources/app_strings.dart';
import 'package:ecommerce_app/config/routes/route_manager.dart';
import 'package:ecommerce_app/core/api/end_points.dart';
import 'package:ecommerce_app/core/base_widgets/loading_widget.dart';
import 'package:ecommerce_app/core/base_widgets/snackbar_widget.dart';
import 'package:ecommerce_app/core/enum/enum_generation.dart';
import 'package:ecommerce_app/core/failure/failure.dart';
import 'package:ecommerce_app/core/responsive_manager/responsive_extensions.dart';
import 'package:ecommerce_app/core/shared_models/pagination/pagination_model.dart';
import 'package:ecommerce_app/core/shared_models/product/product_entity.dart';
import 'package:ecommerce_app/core/shared_models/product/product_model.dart';
import 'package:ecommerce_app/core/shared_widget/empty_list_widget.dart';
import 'package:ecommerce_app/core/shared_widget/header_for_more.dart';
import 'package:ecommerce_app/core/shared_widget/loading_shimmer_list.dart';
import 'package:ecommerce_app/my_app/app_reference.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';

import '../../../../config/base_local_data_source/base_local_data_source.dart';
import '../../../../config/base_remote_data_source/base_remote_data_source.dart';
import '../../../../config/base_repository/base_repository.dart';
import '../home/home.dart';

part 'data/saved_data_source/saved_local_data_source.dart';
part 'data/saved_data_source/saved_remote_data_source.dart';
part 'data/saved_models/saved_entity.dart';
part 'data/saved_models/saved_model.dart';
part 'data/saved_repository/saved_repository.dart';
part 'logic/saved_bloc.dart';
part 'logic/saved_event.dart';
part 'logic/saved_state.dart';
part 'ui/saved_screen/saved_screen.dart';
part 'ui/saved_widgets/saved_widgets.dart';
