// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxaw-TgcUaUx7GynShHCL15yRP1gjTEc',
    appId: '1:900748519307:web:09515ca048053fe7ddb18e',
    messagingSenderId: '900748519307',
    projectId: 'ecommerce-app-f1e5a',
    authDomain: 'ecommerce-app-f1e5a.firebaseapp.com',
    storageBucket: 'ecommerce-app-f1e5a.firebasestorage.app',
    measurementId: 'G-MXCL2GZ3LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRQEizGv-ipR68jYeME7RNShcajhCkz6w',
    appId: '1:900748519307:android:67318702f0038627ddb18e',
    messagingSenderId: '900748519307',
    projectId: 'ecommerce-app-f1e5a',
    storageBucket: 'ecommerce-app-f1e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNlZUiGZfqTqK-xoVPhJBJ0kIwgiQi5Y',
    appId: '1:900748519307:ios:3ee8abd30a588631ddb18e',
    messagingSenderId: '900748519307',
    projectId: 'ecommerce-app-f1e5a',
    storageBucket: 'ecommerce-app-f1e5a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
